// <auto-generated />
using JsonColumnBD.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JsonColumnBD.Migrations
{
    [DbContext(typeof(DbContextSales))]
    [Migration("20230628005512_CreatingDb")]
    partial class CreatingDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JsonColumnBD.Models.Sales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("sales");
                });

            modelBuilder.Entity("JsonColumnBD.Models.Sales", b =>
                {
                    b.OwnsOne("JsonColumnBD.Models.Customer", "Customer", b1 =>
                        {
                            b1.Property<int>("SalesId")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SalesId");

                            b1.ToTable("sales");

                            b1.ToJson("Customer");

                            b1.WithOwner()
                                .HasForeignKey("SalesId");

                            b1.OwnsOne("JsonColumnBD.Models.Direccion", "DireccionCus", b2 =>
                                {
                                    b2.Property<int>("CustomerSalesId")
                                        .HasColumnType("int");

                                    b2.Property<string>("name")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("CustomerSalesId");

                                    b2.ToTable("sales");

                                    b2.WithOwner()
                                        .HasForeignKey("CustomerSalesId");
                                });

                            b1.Navigation("DireccionCus");
                        });

                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
